steps:
# build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/teams-notify:$COMMIT_SHA', '.']
# push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/teams-notify:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'teams-notify'
  - '--image'
  - 'gcr.io/$PROJECT_ID/teams-notify:$COMMIT_SHA'
  - '--region'
  - 'us-east1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--set-env-vars APP_ID=$$APP_ID, APP_PASSWORD=$$APP_PASSWORD, PROJECT_ID=$PROJECT_ID'
  secretEnv: 
  - 'APP_ID'
  - 'APP_PASSWORD'

images:
- 'gcr.io/$PROJECT_ID/teams-notify:$COMMIT_SHA'

secrets:
- kmsKeyName: 'projects/epam-trainings/locations/global/keyRings/epam/cryptoKeys/teams-notify'
  secretEnv:
    APP_ID: "CiQAKvD3Fy6zdANTIppF0JBJSLI6zXiakg2JMHBp1FT7QXsTU4QSTQDPQ28iM+OCTuqe/MY8Z87WHWrzwCSVhgBcu3k0/g1KmpR0x8oQngv1zpnCjfkw7MZEttpv9U2mpVO25X5P9eGvhHkkVfSv29oFKEs6"
    APP_PASSWORD: "CiQAKvD3FxCCon0Yl/kfzjjYiI48fyCG00Ogk1CPHY9/qjvxMO4SSQDPQ28iUFbOJ7I/kaaJmetVwcLUQTUGl3fWpHgJZ1Lx+u4zk6trdteCOyUWQ6mmSNNspiZSNSLm6VQ4dQl1Ms0Kc2RymlWZGOU="